language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
  - "pypy"

env:
  global:
    - WAIT_FOR_ES=1
    - ES_PY_VERSION=master
  matrix:
    - ES_VERSION=7.0.0

matrix:
  include:
    - python: 3.8
      install:
        - python -m pip install nox
      script:
        - nox -s lint
  allow_failures:
    - python: "nightly"

install:
  - mkdir /tmp/elasticsearch
  - wget -O - https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}-linux-x86_64.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - /tmp/elasticsearch/bin/elasticsearch -d
  - travis_retry pip install --upgrade pytest
  - travis_retry pip install git+https://github.com/elastic/elasticsearch-py.git@${ES_PY_VERSION}#egg=elasticsearch

script:
  - python setup.py test
